;   Copyright (c) Rich Hickey. All rights reserved.
;   The use and distribution terms for this software are covered by the
;   Eclipse Public License 1.0 (http://opensource.org/licenses/eclipse-1.0.php)
;   which can be found in the file epl-v10.html at the root of this distribution.
;   By using this software in any fashion, you are agreeing to be bound by
;   the terms of this license.
;   You must not remove this notice, or any other, from this software.

(ns ^{:doc "ClojureDart port of clojure.spec.test.alpha."
      :author "Rich Hickey"}
  cljd.spec.test.alpha)

;; TODO: port from clojurescript src/main/cljs/cljs/spec/test/alpha.cljs