#!/usr/bin/env bash

rm -rf tmp/tests
mkdir -p tmp/tests/src/cljd
cat > tmp/tests/deps.edn <<EOF
{:paths ["src"] ; where your cljd files are
 :deps {org.clojure/clojure {:mvn/version "1.10.1"}
        tensegritics/clojuredart
        {:local/root "../../"}}
 :cljd/opts {:main cljd.run-tests
             :kind :dart}}
EOF

cd tmp/tests
clojure -M -m cljd.build init
dart pub add -d test
cat > src/cljd/run_tests.cljd <<EOF
(ns ci.core
  (:require
    cljd.test-clojure.core-test-cljd
    cljd.test-clojure.string
    cljd.test-clojure.core-test
    cljd.test-clojure.for
    cljd.test-clojure.clojure-zip
    cljd.test-reader.reader-test))
EOF
clojure -M -m cljd.build compile cljd.test-clojure.core-test-cljd cljd.test-clojure.string cljd.test-clojure.core-test cljd.test-clojure.for cljd.test-clojure.clojure-zip cljd.test-reader.reader-test
dart test -p vm
