#!/usr/bin/env bash

PATH="$PWD/.fvm/flutter_sdk/bin:$PATH"

set -e

rm -rf tmp/tests
mkdir -p tmp/tests/src/cljd
cat > tmp/tests/deps.edn <<EOF
{:paths ["src"] ; where your cljd files are
 :deps {tensegritics/clojuredart
        {:local/root "../../"}}
 :cljd/opts {:main cljd.run-tests
             :kind :dart}}
EOF

cd tmp/tests
clojure -M -m cljd.build init
dart pub add -d test || true
clojure -M -m cljd.build compile cljd.test-clojure.core-test-cljd cljd.test-clojure.string cljd.test-clojure.core-test cljd.test-clojure.for cljd.test-clojure.clojure-zip cljd.test-clojure.clojure-set cljd.test-clojure.clojure-walk cljd.test-clojure.other-functions cljd.test-clojure.test-test cljd.test-reader.reader-test cljd.test-clojure.primitives-test cljd.test-clojure.data cljd.test-clojure.parse
# --enable-experiment=records is there for making tests pass even on dart2
# on dart3 it should be a no op.
dart --enable-experiment=records test -p vm
