name: audio_service_example
description: Demonstrates how to use the audio_service plugin.
publish_to: 'none'

environment:
  sdk: ">=2.14.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.0.1
  audio_session: ^0.1.20
  just_audio: ^0.9.39
  flutter_tts: ^3.8.3
  device_info_plus: ^9.1.0
  android_content_provider: ^0.4.1
  permission_handler : ^11.0.1
  rxdart: ^0.27.2
  audio_service_mpris: ^0.1.3
  just_audio_mpv: ^0.1.7
  audio_service: ^0.18.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true