(ns sample.fizzbuzz
  (:require
   ["package:flutter/material.dart" :as m]
   [cljd.flutter :as f]))

(def ^m/TextStyle text-style (m/TextStyle .fontWeight m/FontWeight.w700 .fontSize 32))

(def fa (fn [a b] (m/Text "ya ")))

(defn caca []
  (m/ListView.builder .itemBuilder (identity fa)))

(defn main []
  (f/run
    (m/MaterialApp .title "Fizz buzz Demo")
    .home
    (m/Scaffold .appBar (m/AppBar .title (m/Text "Fizz buzz Demo")))
    .body
    m/Center
    #_(m/Text "Heyllo")
    (caca)))
