;; Copyright (c) Rich Hickey. All rights reserved.
;; The use and distribution terms for this software are covered by the
;; Eclipse Public License 1.0 (http://opensource.org/licenses/eclipse-1.0.php)
;; which can be found in the file epl-v10.html at the root of this distribution.
;; By using this software in any fashion, you are agreeing to be bound by
;; the terms of this license.
;; You must not remove this notice, or any other, from this software.

(ns cljd.test-clojure.edn-test
  (:use [cljd.test :only [deftest is testing]])
  (:require [cljd.edn :as edn]
            [cljd.reader :as reader]))

(deftest test-read-string
  (testing "Mirrors cljs.reader/read-string"
    (is (= (edn/read-string "(+ 1 2)")
           (reader/read-string "(+ 1 2)")))
    (is (= (edn/read-string "{:a #{[1]}}")
           (reader/read-string "{:a #{[1]}}")))))
