;   Copyright (c) Rich Hickey. All rights reserved.
;   The use and distribution terms for this software are covered by the
;   Eclipse Public License 1.0 (http://opensource.org/licenses/eclipse-1.0.php)
;   which can be found in the file epl-v10.html at the root of this distribution.
;   By using this software in any fashion, you are agreeing to be bound by
;   the terms of this license.
;   You must not remove this notice, or any other, from this software.

; Author: Frantisek Sodomka

;;
;;  Created 1/28/2009

(ns cljd.test-clojure.predicates
  (:use [clojure.test :only [deftest is are]]))


;; *** Type predicates ***

#_(def myvar 42)

(def sample-data {
  :nil nil

  :bool-true true
  :bool-false false

  ;; :byte   (byte 7)
  ;; :short  (short 7)
  :int    (int 7)
  :long   (long 7)
  ;; :bigint (bigint 7)
  :float  (float 7)
  :double (double 7)
  ;; :bigdec (bigdec 7)

  ;; :ratio 2/3

  ;; :character \a
  :symbol 'abc
  :keyword :kw

  :empty-string ""
  :empty-regex #""
  :empty-list ()
  :empty-lazy-seq (lazy-seq nil)
  :empty-vector []
  :empty-map {}
  :empty-set #{}
  :empty-array (into-array [])

  :string "abc"
  :regex #"a*b"
  :list '(1 2 3)
  :lazy-seq (lazy-seq [1 2 3])
  :vector [1 2 3]
  :map {:a 1 :b 2 :c 3}
  :set #{1 2 3}
  :array (into-array [1 2 3])

  :fn (fn [x] (* 2 x))

  :class DateTime
  :object (DateTime/now)

  ;; :var (var myvar)
  :delay (delay (+ 1 2))
})


(def type-preds {
  nil? [:nil]

  true?  [:bool-true]
  false? [:bool-false]
  ; boolean?

  integer?  [:byte :short :int :long :bigint]
  float?    [:float :double]
  ;; decimal?  [:bigdec]
  ;; ratio?    [:ratio]
  ;; rational? [:byte :short :int :long :bigint :ratio :bigdec]
  number?   [:byte :short :int :long :bigint :ratio :bigdec :float :double]

  ; character?
  symbol?  [:symbol]
  keyword? [:keyword]

  string? [:empty-string :string]
  ; regex?

  list?   [:empty-list   :list]
  vector? [:empty-vector :vector]
  map?    [:empty-map    :map]
  set?    [:empty-set    :set]

  coll? [:empty-list     :list
         :empty-lazy-seq :lazy-seq
         :empty-vector   :vector
         :empty-map      :map
         :empty-set      :set]

  seq?  [:empty-list     :list
         :empty-lazy-seq :lazy-seq]
  ; array?

  fn?  [:fn]
  ifn? [:fn
        :empty-vector :vector :empty-map :map :empty-set :set
        :keyword :symbol :var]

  ;; class? [:class]
  ;; var?   [:var]
  delay? [:delay]
})


;; Test all type predicates against all data types
;;
(defn- get-fn-name [f]
  (str
    (apply str (nthnext (first (.split (str f) "_"))
                        (count "clojure.core$")))
    "?"))

(deftest test-type-preds
  (doseq [tp type-preds]
    (doseq [dt sample-data]
      (if (some #(= % (first dt)) (second tp))
        (is ((first tp) (second dt))
          (pr-str (list (get-fn-name (first tp)) (second dt))))
        (is (not ((first tp) (second dt)))
          (pr-str (list 'not (list (get-fn-name (first tp)) (second dt)))))))))


;; Additional tests:
;; http://groups.google.com/group/clojure/browse_thread/thread/537761a06edb4b06/bfd4f0705b746a38
;;
(deftest test-string?-more
  (are [x] (not (string? x))
    (new StringBuffer "abc")
    (new StringBuffer "xyz")))

(def pred-val-table
  (let [now (DateTime/now)
        uuid (random-uuid)
        ;; barray (byte-array 0)
        iarray (int-array 0)
        uri (Uri/parse "http://clojure.org")]
    [[identity   int?  pos-int?  neg-int?  nat-int?  double? boolean? indexed? seqable? reversible? ident? uuid? #_decimal? inst? uri?  #_bytes?]
     [0          true  false     false     true      false   false    false    false    false       false  false #_false    false false #_false]
     [1          true  true      false     true      false   false    false    false    false       false  false #_false    false false #_false]
     [-1         true  false     true      false     false   false    false    false    false       false  false #_false    false false #_false]
     [1.0        false false     false     false     true    false    false    false    false       false  false #_false    false false #_false]
     [true       false false     false     false     false   true     false    false    false       false  false #_false    false false #_false]
     [[]         false false     false     false     false   false    true     true     true        false  false #_false    false false #_false]
     [nil        false false     false     false     false   false    true     true     false       false  false #_false    false false #_false]
     [{}         false false     false     false     false   false    false    true     false       false  false #_false    false false #_false]
     [:foo       false false     false     false     false   false    false    false    false       true   false #_false    false false #_false]
     ['foo       false false     false     false     false   false    false    false    false       true   false #_false    false false #_false]
     #_[0.0M       false false     false     false     false   false    false    false    false       false  false #_true     false false #_false]
     #_[0N         false false     false     false     false   false    false    false    false       false  false #_false    false false #_false]
     [uuid       false false     false     false     false   false    false    false    false       false  true  #_false    false false #_false]
     [uri        false false     false     false     false   false    false    false    false       false  false #_false    false true  #_false]
     [now        false false     false     false     false   false    false    false    false       false  false #_false    true  false #_false]
     [iarray     false false     false     false     false   false    true     true     false       false   false #_false    false false #_false]
     #_[barray     false false     false     false     false   false    false    true     false       false  false #_false    false false #_true]]))

(deftest test-preds
  (let [[preds & rows] pred-val-table]
    (doseq [row rows]
      (let [v (first row)]
        (dotimes [i (count row)]
          (is (= ((nth preds i) v) (nth row i))
              (pr-str (list (get-fn-name (nth preds i)) v))))))))

(deftest test-sorted?
  (are [x] (not (sorted? x))
    nil
    0
    -1.0
    true
    :abc
    ""
    []
    #{}
    {}
    [1 2 3])
  (are [x] (sorted? x)
    (sorted-map)
    (sorted-map-by compare :foo :bar)
    (sorted-set)
    (sorted-set-by compare :foo :bar)))

;; Special double predicates

(deftest test-double-preds
  (is (NaN? ##NaN))
  (is (NaN? (double/parse "NaN")))
  (is (NaN? double/nan))
  (is (not (NaN? 5)))
  ; Compilation error in Dart
  ;; (is (not (NaN? -5)))
  (let [nil-value nil
        kw-value  :xyz]
    (is (thrown? Error (NaN? nil-value)))
    (is (thrown? Error (NaN? kw-value))))

  (is (infinite? ##Inf))
  (is (infinite? ##-Inf))
  (is (infinite? double/infinity))
  (is (infinite? double/negativeInfinity))
  (is (not (infinite? 5)))
  ; Compilation error in Dart
  ;; (is (not (infinite? -5)))
  (let [nil-value nil
        kw-value  :xyz]
    (is (thrown? Error (infinite? nil-value)))
    (is (thrown? Error (infinite? kw-value))))
  )

(deftest test-special-symbol?
  (are [x] (not (special-symbol? x))
    nil
    true
    false
    "foo"
    0
    0.0
    :foo
    'foo/bar
    'defn
    'require
    'letfn*
    'ns/ns)
  (are [x] (special-symbol? x)
    '. '& 'set! 'if 'def 'throw 'new 'ns 'try 'catch 'finally 'do 'var 'letfn 'quote 'recur
    'dart/is? 'dart/await 'dart/async-barrier 'dart/run-zoned 'dart/assert 'dart/type-like
    'case* 'let* 'loop* 'fn* 'reify* 'deftype* 'defprotocol* 'defmethod* 'defmulti* 'extend-type-protocol*))